global:
  project: ""
  argocd:
    namespace: argocd
    targetRevision: main
    syncPolicy: {}

namespace: ""

project: ""

flagship:
  enabled: true
  syncWave: 0
  repoURL: git@github.com:hungrysushi/nautilus_charts.git
  path: charts/flagship
  targetRevision: ""
  syncPolicy: {}
  values: {}

fleet:
  enabled: true
  defaults:
    syncWave: 1
    repoURL: git@github.com:hungrysushi/nautilus_charts.git
    path: charts/app-service
    targetRevision: ""
    syncPolicy: {}
  ships: []
#   name: ""
#   namespace: ""
#   repoURL: ""
#   path: ""
#   targetRevision: ""
#   syncPolicy: {}
#   values: {}

flotilla:
  enabled: false
  syncWave: 1
  repoURL: git@github.com:hungrysushi/nautilus_charts.git
  path: charts/flotilla
  targetRevision: ""
  syncPolicy: {}
  values: {}
