{{- if .Values.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Release.Name }}-istio-node-gateway
  namespace: {{ include "flagship.namespace" . }}
  {{- if (include "flagship.enableFinalizer" .) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.istio.syncWave | quote }}
spec:
  project: {{ .Values.project | default .Values.global.project | default "default" }}
  source:
    path: {{ .Values.istio.nodeGateway.chart }}
    repoURL: {{ .Values.istio.nodeGateway.repoURL}}
    targetRevision: {{ .Values.istio.nodeGateway.targetRevision | default .Values.global.argocd.targetRevision }}
    helm:
      releaseName: istio-nodegateway
      valueFiles:
        - values.yaml
{{- with .Values.istio.nodeGateway.values }}
      values: |
        {{- toYaml . | nindent 8 }}
{{- end }}
  destination:
    namespace: {{ .Values.istio.nodeGateway.namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
  {{- with .Values.syncPolicy | default .Values.global.argocd.syncPolicy }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
