{{- if .Values.istio.enabled }}
{{- range $gateway := .Values.istio.gateways }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Release.Name }}-istio-gateway-{{ $gateway.name }}
  namespace: {{ include "flagship.namespace" $ }}
  {{- if (include "flagship.enableFinalizer" $) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.istio.syncWave | quote }}
spec:
  project: {{ $.Values.project | default $.Values.global.project | default "default" }}
  source:
    chart: gateway
    repoURL: {{ $.Values.istio.repoURL }}
    targetRevision: {{ $.Values.istio.targetRevision }}
    helm:
      releaseName: istio-gateway-{{ $gateway.name }}
      valueFiles:
        - values.yaml
      values: |
{{- with $gateway.values }}
        {{- toYaml . | nindent 8 }}
{{- end }}
  destination:
    namespace: {{ $gateway.namespace }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
  {{- with $.Values.syncPolicy | default $.Values.global.argocd.syncPolicy }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
