global:
  project: ""
  argocd:
    namespace: argocd
    targetRevision: main
    syncPolicy: {}

namespace: ""

project: ""

syncPolicy: {}

clusterResources:
  syncWave: -3
  namespaces: []

argocd:
  enabled: true
  repoURL: 'https://argoproj.github.io/argo-helm'
  chart: argo-cd
  targetRevision: 5.*
  syncWave: -2
  values: {}

istio:
  enabled: true
  syncWave: -1

networking:
  enabled: true
  syncWave: 0
