global:
  project: ""
  argocd:
    enableFinalizer: false
    namespace: argocd
    targetRevision: main
    syncPolicy: {}

namespace: ""

project: ""

enableFinalizer: ""

syncPolicy: {}

clusterResources:
  syncWave: -3
  namespaces: []

argocd:
  enabled: true
  repoURL: 'https://argoproj.github.io/argo-helm'
  chart: argo-cd
  targetRevision: 5.*
  syncWave: -2
  values: {}

istio:
  enabled: true
  syncWave: -1
  repoURL: 'https://istio-release.storage.googleapis.com/charts'
  targetRevision: '1.16.0'
  base:
    namespace: istio-system
    values: {}
  istiod:
    namespace: istio-system
    values: {}
  gateways: []
# - name: ingressgateway
#   namespace: istio-ingress
#   values: {}
  nodeGateway:
    # special gateway for cheap ingress through host ports. Not for production use
    namespace: istio-ingress
    chart: charts/gateway
    repoURL: git@github.com:hungrysushi/nautilus_charts.git
    targetRevision: ""
    values: {}

networking:
  enabled: true
  syncWave: 0

certManager:
  enabled: true
  syncWave: 0
  repoURL: https://charts.jetstack.io
  targetRevision: v1.10.1
  namespace: cert-manager
  values:
    installCRDs: true
