global:
  project: ""
  argocd:
    namespace: argocd
    targetRevision: main
    syncPolicy: {}

namespace: ""

project: ""

syncPolicy: {}

clusterResources:
  syncWave: -3
  namespaces: []

argocd:
  enabled: true
  repoURL: 'https://argoproj.github.io/argo-helm'
  chart: argo-cd
  targetRevision: 5.*
  syncWave: -2
  values: {}

istio:
  enabled: true
  syncWave: -1
  repoURL: 'https://istio-release.storage.googleapis.com/charts'
  targetRevision: '1.16.*'
  base:
    namespace: istio-system
    values: {}
  istiod:
    namespace: istio-system
    values: {}
  gateways: []
# - name: ingressgateway
#   namespace: istio-ingress
#   values: {}

networking:
  enabled: true
  syncWave: 0
