{{- if .Values.fleet.enabled }}
{{- range .Values.fleet.ships }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Release.Name }}-fleet-ship-{{ .name }}
  namespace: {{ include "shipyard.namespace" $ }}
  {{- if (include "shipyard.enableFinalizer" .) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.fleet.defaults.syncWave | quote }}
spec:
  project: {{ $.Values.project | default $.Values.global.project | default "default" }}
  source:
    repoURL: {{ .repoURL | default $.Values.fleet.defaults.repoURL }}
    path: {{ .path | default $.Values.fleet.defaults.path }}
    targetRevision: {{ .targetRevision | default $.Values.fleet.defaults.targetRevision | default $.Values.global.argocd.targetRevision }}
    helm:
      releaseName: {{ $.Release.Name }}-fleet-ship-{{ .name }}
      valueFiles:
        - values.yaml
      values: |
      {{- with .values }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
  destination:
    namespace: {{ include "shipyard.fleet.destinationNamespace" (dict "root" $ "ship" .) }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
  {{- with .syncPolicy | default $.Values.fleet.defaults.syncPolicy | default $.Values.global.argocd.syncPolicy }}
    {{ toYaml . | nindent 4}}
  {{- end }}
{{- end }}
{{- end }}
