{{- if .Values.flotilla.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-flotilla
  namespace: {{ include "shipyard.namespace" . }}
spec:
  project: {{ .Values.project | default .Values.global.project | default "default" }}
  source:
    repoURL: {{ .Values.flotilla.repoURL }}
    path: {{ .Values.flotilla.path }}
    targetRevision: {{ .Values.flotilla.targetRevision | default .Values.global.argocd.targetRevision }}
    helm:
      releaseName: {{ .Release.Name }}-flotilla
      valueFiles:
        - values.yaml
      {{- with .Values.flotilla.values }}
      values: |
        {{ toYaml . | nindent 8 }}
      {{- end }}
  destination:
    namespace: {{ include "shipyard.namespace" . }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
  {{- with .Values.flotilla.syncPolicy | default .Values.global.argocd.syncPolicy }}
    {{ toYaml . | nindent 4}}
  {{- end }}
{{- end }}
