{{- if .Values.flotilla.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-flotilla
  namespace: {{ include "shipyard.namespace" . }}
  {{- if (include "shipyard.enableFinalizer" .) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.flotilla.syncWave | quote }}
spec:
  project: {{ .Values.project | default .Values.global.project | default "default" }}
  source:
    repoURL: {{ .Values.flotilla.repoURL }}
    path: {{ .Values.flotilla.path }}
    targetRevision: {{ .Values.flotilla.targetRevision | default .Values.global.argocd.targetRevision }}
    helm:
      releaseName: {{ .Release.Name }}-flotilla
      valueFiles:
        - values.yaml
      values: |
        global: {{ toYaml .Values.global | nindent 10 }}
      {{- with .Values.flotilla.values }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
  destination:
    namespace: {{ include "shipyard.namespace" . }}
    server: 'https://kubernetes.default.svc'
  syncPolicy:
  {{- with .Values.flotilla.syncPolicy | default .Values.global.argocd.syncPolicy }}
    {{ toYaml . | nindent 4}}
  {{- end }}
{{- end }}
